### ISSUE TITLE
Add ZCash

### ISSUE THREAD

**Issue by beardog108** [onlineth/Keybase.io-Card-Node.js#1]
Keybase now has the cryptocurrency ZCash, but this doesn't reflect on your badges.

https://keybase.io/blog/keybase-and-zcash

**Comment by onlineth** [comment]
Excellent point, I'll work on adding this over the next few days.

**Comment by onlineth** [comment]
ZCash icon support added with commit https://github.com/onlineth/Keybase.io-Card-Node.js/commit/f63ee5c5e4ea5f03777a35fcf9b410c1197bc7ac

https://keybase.onlineth.com/#beardog

![Default Theme](https://keybase.onlineth.com/beardog.png?theme=default)

![Dark Theme](https://keybase.onlineth.com/beardog.png?theme=dark)
