### ISSUE TITLE
Add Facebook

### ISSUE THREAD

**Issue by beardog108** [onlineth/Keybase.io-Card-Node.js#2]
I don't have a Facebook, but i think its a relatively new Keybase profile feature, and it doesn't appear to be reflected on your badges either.

Thanks :)

**Comment by onlineth** [comment]
This is currently fixed on the live https://keybase.onlineth.com version (which uses the [PHP version](https://github.com/onlineth/Keybase.io-Card-PHP)), going to add a patch to this version too in the future

**Comment by beardog108** [comment]
Great, thanks again.
